site_name: Interactive Components in Plone Classic

theme:
  name: material
  logo: img/logo_icon.png
  palette:
    primary: deep purple

extra:
  homepage: https://www.rohberg.ch

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - footnotes
