site_name: Interactive Components in Plone Classic

theme:
  name: material
  logo: assets/logo.png

extra:
  homepage: https://www.rohberg.ch

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - footnotes